Objective wrapper
Happy-Algorithms-League/hal-cgp pull request #245
Opened 2020-10-30 13:56 UTC by HenrikMettler

Objective wrapper that checks `if individual.fitness is None` and returns `objective(individual, *args)` or the `individual` otherwise.

2020-11-11 00:46 UTC, mschmidt87 requested changes
This is very neat. 

I made one minor suggestion for the docstring and a suggestion to solve the mypy issue.

2020-11-11 00:46 UTC, mschmidt87 commented on cgp/utils.py
> +    Skips evaluations of individuals with fitness != None
perhaps add one more half-sentence like I suggested.

2020-11-11 00:46 UTC, mschmidt87 commented on cgp/utils.py
> +    Skips evaluations of individuals with fitness != None
```suggestion
    Skips evaluations of individuals with fitness != None, i.e., for individuals where the fitness has been evaluated already.
```

2020-11-11 00:46 UTC, mschmidt87 commented on cgp/utils.py
> +
The `mypy` issue can be solved with these suggestions:

2020-11-11 00:46 UTC, mschmidt87 commented on cgp/utils.py
> +) -> Callable[[IndividualBase, Any, Any], IndividualBase]:
```suggestion
F = TypeVar('F', bound=Callable[..., IndividualBase])

def objective(f: F) -> F:
```

2020-11-11 00:46 UTC, mschmidt87 commented on cgp/utils.py
> +
you'll need to import `TypeVar, cast` from `typing`

2020-11-11 00:46 UTC, mschmidt87 commented on cgp/utils.py
> +    return wrapped
```suggestion
    return cast(F, wrapped)
```

2020-11-11 11:59 UTC, mschmidt87 approved these changes
LGTM

2020-11-11 12:02 UTC, jakobj commented
@mschmidt87 what about the discussion in #244?

2020-11-27 00:23 UTC, mschmidt87 commented
See the discussion in #244.

2020-11-27 00:23 UTC, closed without merging