Testing `n_columns=0`
Happy-Algorithms-League/hal-cgp pull request #299
Opened 2021-04-13 16:55 UTC by HenrikMettler

So, weirdly `n_columns = 0` works in the minimal example and in a small test in population it gives the expected sympy expression. However a lower level test fails when calling directly `CartesianGraph(genome).to_sympy()`. Any ideas why? 
Also imo we should rather deprecate the `n_columns=0` or `n_rows=0` functionality, since they don't make much sense anyway. 
Closes #283

2021-04-19 14:46 UTC, jakobj requested changes
great, thanks for working on this! :rocket: 

i've added a few inline comments that should be addressed.

regarding your question: the low-level error was generated because the genome was not initialized. in also, i think we should not explicitly forbid `n_columns=0` if our library does the right thing, why not?

2021-04-19 14:46 UTC, jakobj commented on test/test_genome.py
> +def test_ncolumns_zero():
```suggestion
def test_ncolumns_zero(rng):
```

2021-04-19 14:46 UTC, jakobj commented on test/test_genome.py
> +    print(sympy_expression)
```suggestion
    genome = cgp.Genome(**genome_params)
    genome.randomize(rng)
    
    CartesianGraph(genome).to_func()
    CartesianGraph(genome).to_numpy()
    CartesianGraph(genome).to_torch()
    CartesianGraph(genome).to_sympy()
```

2021-04-19 14:46 UTC, jakobj commented on test/test_population.py
> +    assert sympy_expr[0] == expected_sympy_expr
```suggestion
    for ind in pop:
        sympy_expr = ind.to_sympy()
        assert sympy_expr[0] == sympy.sympify("x_0")
```

2021-04-19 14:46 UTC, jakobj commented on test/test_population.py
> +from sympy import symbols
```suggestion
```

2021-04-19 14:46 UTC, jakobj commented on test/test_population.py
> +
```suggestion
    sympy = pytest.importorskip("sympy")
```

2021-04-26 09:02 UTC, HenrikMettler commented
Ok, i am a bit lost. Somehow the test doesn't pass on the python 3.7 testsuite, however I can't reproduce the error locally. Any ideas why?

2021-04-26 13:01 UTC, mschmidt87 commented
I also tried to reproduce the error locally without success. I also tried to google the error and found this link which might (or might not) be helpful: https://stackoverflow.com/questions/66640404/basic-loop-with-sympy-gives-me-this-error-message-symbol-object-is-not-subsc
Another, a bit brute-force option, is to do:
- remove python 3.7 temporarily to see whether 3.6 and 3.8 throw the same error in the CI
- add some debug output to the test and rerun the CI.
Also, I did create a new conda env with python 3.7 and installed the library, so I basically followed the steps in the CI, but I didn't confirm that the configuration is really exactly identical with the CI environment. So, you could/should also do that with your local environment.

2021-04-27 14:00 UTC, jakobj commented
have you tried rebasing on the most recent master? one of the recent PRs has removed the necessity to do `sympy_expr[0]` if only one expression is encoded in the genome, as it is automatically unpacked. i think this might be where the error comes from.

2021-04-27 15:13 UTC, HenrikMettler commented
ah yes, that was it! my bad, thanks for suggesting

2021-04-28 12:21 UTC, mschmidt87 approved these changes

2021-04-29 17:44 UTC, jakobj approved these changes
looking good! :+1:

and merging

2021-04-29 17:45 UTC, merged