Raise exception if fitness is None after calls to objectives
Happy-Algorithms-League/hal-cgp pull request #333
Opened 2021-06-24 11:42 UTC by jakobj

as the title suggests. this should help to pinpoint bugs in objective functions.

closes #309

2021-07-15 13:46 UTC, HenrikMettler requested changes
Just a small suggestion to make the test easier to understand

2021-07-15 13:46 UTC, HenrikMettler commented on test/test_ea_mu_plus_lambda.py
> +        return ind
Maybe add `# Missing fitness assignement`

2021-07-16 15:20 UTC, HenrikMettler commented on test/test_ea_mu_plus_lambda.py
> +    def objective(ind):
```suggestion
def test_objective_must_set_valid_fitness(population_params, genome_params, ea_params):
    def objective(ind):
        # missing ind.fitness assignement
```

2021-08-06 12:10 UTC, jakobj commented
CI is happy, if you're happy, please approve this PR @HenrikMettler so we can merge it

2021-08-18 09:49 UTC, jakobj commented
ping @HenrikMettler

2021-08-18 10:19 UTC, HenrikMettler approved these changes
LGTM, not sure who needs to squish the commits

2021-09-20 13:26 UTC, HenrikMettler commented
> LGTM, not sure who needs to squish the commits

ping @jakobj

2021-11-03 13:05 UTC, jakobj commented
squashed and pushed. let's see whether CI is happy :)

2021-11-03 15:19 UTC, merged